### ISSUE TITLE
Possible test flake in /test/e2e/cli/pkg_test.go

### ISSUE THREAD

**Issue by jake-ciolek** [unikraft/kraftkit#735] opened 2023-08-22 10:57 UTC
### Describe the bug

One of the kraftkit e2e tests failed and then succeeded on a re-run. Investigate why it's flaky.

[/test/e2e/cli/pkg_test.go](https://github.com/unikraft/kraftkit/blob/staging/test/e2e/cli/pkg_test.go#L52)

See:

https://github.com/unikraft/kraftkit/actions/runs/5937551919/job/16100190919

**Comment by craciunoiuc** [comment] 2023-09-12 07:51
I saw this happen several times, but I can't quite get it to fail locally.

I think, as this downloads stuff over the internet, there is a non-negligible chance that sometimes tests will fail.

We could retry the test if it fails once, but it's so rare we can just do by hand I think.

**Comment by craciunoiuc** [comment] 2023-09-15 14:26
Ran the command several tens of times and couldn't reproduce anymore with the changes in https://github.com/unikraft/kraftkit/pull/817

This then means that there were two possible reasons:
 * Indeed there was a parsing error from using the default logger that is fixed by switching to json
 * The manifest server was down and the command actually failed

**Closed as completed** 2023-09-15 15:07 UTC
Labels: kind/bug, good-first-issue, area/test
