### ISSUE TITLE
Running kraftkit without `sudo` runs much slower

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraftkit#560] opened 2023-07-01 07:49 UTC
### Describe the bug

After running the `hello-world` application I tried to use `kraft ps` command.
Running `kraft ps` takes much longer(2 seconds) than `sudo kraft ps`.

### Steps to reproduce

```bash
git clone --depth=1 https://github.com/unikraft/app-helloworld.git;
cd app-helloworld;
kraft build --plat qemu --arch x86_64;
kraft run
```

```bash
kraft ps
```

Also, I think this is the same with all kraft commands.
Running as `sudo` it much faster.

### Expected behavior

Both `kraft ps` and `sudo kraft ps` commands should run at the same fast.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by antoineco** [comment] 2023-07-01 07:54
@gabrielmocanu I noticed a similar behavior recently. Is `kraft version` also slow?

**Comment by gabrielmocanu** [comment] 2023-07-01 08:04
> @gabrielmocanu I noticed a similar behavior recently. Is `kraft version` also slow?

Nope. For `kraft version` I don't see this problem.

**Comment by craciunoiuc** [comment] 2023-07-01 13:23
I can't reproduce this :cry: 

@nderjung has no chance to reproduce because his computer does not support more than one user

@antoineco can you investigate this when you have time?

**Comment by razvand** [comment] 2023-07-03 19:39
@antoineco , @gabrielmocanu , @nderjung , @craciunoiuc , I can also reproduce it on my side:

This basically hangs:

```console
kraft run
```

This gives out an error:

```console
$ sudo kraft run
select target: helloworld (qemu-x86_64)
could not start and wait for QEMU process: exit status 1
```

**Comment by craciunoiuc** [comment] 2023-07-03 20:27
> @antoineco , @gabrielmocanu , @nderjung , @craciunoiuc , I can also reproduce it on my side:
> 
> This basically hangs:
> 
> ```
> kraft run
> ```
> 
> This gives out an error:
> 
> ```
> $ sudo kraft run
> select target: helloworld (qemu-x86_64)
> could not start and wait for QEMU process: exit status 1
> ```

In your first case, it hangs, yes, we need to fix this

In the second case, I think I also saw this behaviour on @StefanJum 's laptop. It's because of a very old qemu version. He had 4 (I remember you have 2).

When he tried the container which has 7, it worked fine.

**Comment by StefanJum** [comment] 2023-07-04 04:05
> In the second case, I think I also saw this behaviour on @StefanJum 's laptop. It's because of a very old qemu version. He had 4 (I remember you have 2).
> 
> When he tried the container which has 7, it worked fine.


@craciunoiuc note that this did not happen only for qemu 4, it also happens for qemu latest version,`8.0.2`, which I also tried.

**Comment by craciunoiuc** [comment] 2023-07-04 07:17
`qemu 8.0.2` deprecates an argument we currently use everywhere, that I know it doesn't work 😅

**Comment by nderjung** [comment] 2023-07-05 17:29
We have now added better error reporting to the QEMU invocation which will tell you what the underlying error is. Worth re-trying to get a better handle on the issue at hand.

**Comment by antoineco** [comment] 2023-07-31 07:10
On the current `staging`, `kraft ps` without `sudo` still takes >10s to return, and returns without any information instead of failing:

![image](https://github.com/unikraft/kraftkit/assets/3299086/da82a97b-92b5-4013-902d-142e6012270a)

The output with `sudo`, just as a reference:

![image](https://github.com/unikraft/kraftkit/assets/3299086/b15cf21b-4ff6-4dc4-a7ec-9aa6c7b0273a)

**Comment by nderjung** [comment] 2023-07-31 07:16
Have you incorporated the latest file/group permission changes from #630 ? (i.e. updating `/var/kraftkit` to use group `kraftkit`)

**Comment by craciunoiuc** [comment] 2023-07-31 07:17
Or change the runtime directory 🪄

**Comment by antoineco** [comment] 2023-07-31 07:19
I built `kraft` from staging and ran it.

If the user needs to fiddle with permissions manually on their machine the issue isn't "fixed".

**Comment by nderjung** [comment] 2023-07-31 07:21
Agree. KraftKit should be re-chown-ing the runtimedir if it is UID=0 and the group differs from one set in the settings.

**Comment by antoineco** [comment] 2023-07-31 07:24
Also, my current system doesn't have a `kraftkit` group, so even if kraftkit was attempting something like that, it would fail.
Where does this requirement come from?

**Comment by nderjung** [comment] 2023-07-31 07:27
This becomes more complicated. Understandably, KraftKit should resolve this issue by itself such that users spend zero to minimal amounts of time troubleshooting, especially between versions. I think adding a group to the host would be best covered under [a more general `kraft setup` command](https://github.com/unikraft/kraftkit/issues/213) that could be used to properly install / update the host based on its environment and requirements such as these. (And re-run after upgrades).

For now, the `kraftkit` group is handled by the installation script. This should be migrated to a `kraft setup` command that is first subcommand that is called after its installation and can be used also during upgrades.

**Comment by antoineco** [comment] 2023-07-31 07:40
What about the requirement for this group, where does it come from? If the user needs to run commands that access resources on the filesystem which they don't have permissions on, running those commands requires `sudo` anyway, regardless of whether the group is `kraftkit` or `root`.

**Comment by nderjung** [comment] 2023-07-31 07:52
Not if a common group is added that a user is part of and the group owns these resources. This is the idea behind `chown`ing the runtime directory `/var/kraftkit`. Then multiple users can read and write to this common path.

By far the easiest solution here is to change `--runtime-dir` config value to somewhere owned by the user such that they do not have to use `sudo`.

**Comment by antoineco** [comment] 2023-07-31 07:55
Absolutely. IMO this should be the default (e.g. HOME directory), and multi-user should be an opt-in mode that people need to set up.

**Comment by nderjung** [comment] 2023-07-31 09:59
In fact we have a mechanism for looking up the state directory (it's just never used) This should be set when the config is first created:

https://github.com/unikraft/kraftkit/blob/e212961dbe4e91c793f650a14d3a1d3f1596d4c5/config/config_file.go#L72-L93

**Comment by craciunoiuc** [comment] 2023-08-02 07:34
These look good, but I think the actual fix for this is to find out in which command it blocks, and make it exit early with an error. I think I can look into this

**Comment by craciunoiuc** [comment] 2023-09-09 10:41
I think we can safely close this

If anyone still has this issue they can just reset their `~/.config/kraftkit/config.yaml` file, or just change the `runtime_dir` path inside it

**Closed as completed by craciunoiuc** 2023-09-09 10:41 UTC
Labels: kind/bug
